#!/bin/bash

alias ..="cd .."

alias ap="ansible-playbook"
alias ans="ansible -m shell -u ubuntu -a"

# Git shortcuts
alias g="git"
alias gs="git status"
alias gd="git diff"
alias gds="git diff --staged"
alias gc="git commit -sm"
alias ga="git add"
