#!/bin/sh

DOTFILES_DIR=`pwd`

echo "Linking vim and vimrc"
[ -f $HOME/.vimrc ] && rm $HOME/.vimrc
[ -d $HOME/.vim ] && rm -r $HOME/.vim
ln -s $DOTFILES_DIR/vimrc $HOME/.vimrc
ln -s $DOTFILES_DIR/vim $HOME/.vim
