#!/bin/bash

set -euo pipefail


DOTFILES_DIR=`pwd`

echo "Linking vim and vimrc"
[ -f $HOME/.vimrc ] && rm $HOME/.vimrc
[ -d $HOME/.vim ] && rm -r $HOME/.vim
ln -s $DOTFILES_DIR/vimrc $HOME/.vimrc
ln -s $DOTFILES_DIR/vim $HOME/.vim

[ ! -d $HOME/dotfiles/vim/bundle/Vundle.vim ] && \
  git clone https://github.com/VundleVim/Vundle.vim $HOME/dotfiles/vim/bundle/Vundle.vim

vim +PluginInstall +qall

echo "Linking bins"
[ ! -d $HOME/bin ] && mkdir $HOME/bin
for bin in `find $DOTFILES_DIR/bin -type f -exec basename {} \;`
do
  [ -f $HOME/bin/$bin ] && rm $HOME/bin/$bin
  ln -s $DOTFILES_DIR/bin/$bin $HOME/bin/$bin
done

echo "Linking tmux config"
[ -f $HOME/.tmux.conf ] && rm $HOME/.tmux.conf
ln -s $DOTFILES_DIR/tmux.conf $HOME/.tmux.conf

echo "Linking dotfiles"
files=(aliases bash_profile exports)
for file in "${files[@]}"
do
  [ -f "$HOME/.$file" ] && rm "$HOME/.$file"
  ln -s "$DOTFILES_DIR/$file" "$HOME/.$file"
done

echo "Updating APT Sources"
sudo apt-get -qq update

echo "System Upgrade"
sudo apt-get -qq dist-upgrade

echo "Installing Packages"
sudo apt-get install -qq \
  ack-grep \
  adduser \
  apt-transport-https \
  automake \
  bash-completion \
  bc \
  bridge-utils \
  build-essential \
  bzip2 \
  ca-certificates \
  coreutils \
  curl \
  dconf-tools \
  dnsutils \
  file \
  findutils \
  gcc \
  git \
  gnupg \
  grep \
  gzip \
  hostname \
  indent \
  iptables \
  jq \
  less \
  libc6-dev \
  locales \
  lsof \
  make \
  mount \
  net-tools \
  network-manager \
  openvpn \
  s3cmd \
  scdaemon \
  shellcheck \
  ssh \
  strace \
  sudo \
  tar \
  tree \
  tzdata \
  unzip \
  vim \
  xclip \
  xcompmgr \
  xz-utils \
  zip \
  --no-install-recommends

echo "Cleaning up APT"
sudo apt-get -qq autoremove
sudo apt-get -qq autoclean
sudo apt-get -qq clean
