#!/bin/bash

export EDITOR=/usr/bin/vim
export HISTSIZE=5000000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups
export HISTIGNORE=" *:ls:cd:cd -:pwd:exit:date:* --help:* -h"

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"
